services:
  gofyne_development:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.local
      args:
        user: $USER
    environment:
      - DISPLAY=$DISPLAY
    command: sleep infinity
    container_name: gofynedevelopment_container
    volumes:
      - ..:/code
      - /tmp/.X11-unix:/tmp/.X11-unix:rw